RUN_STRINGS = (
    "Ahora me ves, ahora no." "ε=ε=ε=ε=┌(;￣▽￣)┘",
    "Regresa aquí!",
    "REEEEEEEEEEEEEEEEEE !!!!!!!",
    "¡Cuidado con la pared!",
    "¡¡No me dejes solo con ellos !!",
    "¡Tienes compañía!",
    "¡Chotto mate!",
    "Yare yare aturdido",
    "* Naruto Run activado *",
    "* Nezuko run activado *",
    "¡Oye, hazte responsable de lo que acabas de hacer!",
    "Que las probabilidades estén siempre a tu favor",
    "Corran todos, simplemente lanzaron una bomba 💣💣",
    "Y desaparecieron para siempre, para no ser vistos nunca más",
    "Cuenta la leyenda, todavía están funcionando",
    "Hasta la vista bebé.",
    "Ah, que desperdicio. Me gustó ese.",
    "Como diría el Doctor ... ¡CORRE!",
)

GIFS = [
    "CgACAgQAAx0CSVUvGgAC7KpfWxMrgGyQs-GUUJgt-TSO8cOIDgACaAgAAlZD0VHT3Zynpr5nGxsE",
    "CgACAgUAAx0CU_rCTAABAjdgX1s4NVaeCls6YaH3p43vgdCRwQIAAqsAA4P_MFUYQhyoR-kgpRsE",
    "CgACAgUAAx0CU_rCTAABAjdSX1s3fq5iEJ64YeQLKI8cD7CSuSEAAlUBAAJu09hW5iqWB0hTPD4bBA",
]

SLAP_SAITAMA_TEMPLATES = (
    "Dame una bofetada más y te silenciaré.",
    "Deja de abofetearme. REEEEEEEEEEEEEE.",
    [
        "Te estoy silenciando por un minuto.",  # normal reply
        "Deja de abofetearme solo porque no puedo silenciarte. REEEEEEEEEE.",  # reply to admin
        "tmute",  # command
        "Cállate!",
        "Silencio!",
    ],
)

SLAP_TEMPLATES = (
    "{user2} Fue asesinado por magia.",
    "{user2} murió de hambre sin caricias",
    "{user2} fue derribado por {user1}.",
    "{user2} se desmayó",
    "{user2} se ha quedado sin Pokémon utilizable! ¡{user2} se ha agotado!",
    "{user2} no tiene Pokémon utilizables! ¡{user2} se desmayó!",
    "{user2} obtuvo rekt.",
    "El melón de {user2} fue dividido por {user1}.",
    "{user2} fue cortado y cortado en cubitos por {user1}.",
    "{user2} jugó a la patata caliente con una granada.",
    "{user2} fue apuñalado por {user1}.",
    "{user2} se comió una granada",
    "{user2} es lo que hay para cenar!",
    "{user2} fue cancelado por {user1}.",
    "{user1} envió spam al correo electrónico de {user2}.",
    "{user1} cifró con RSA a {user2} y eliminó la clave privada.",
    "{user1} puso a {user2} en la zona de amigos.",
    "{user1} abofetea a {user2} con una solicitud de eliminación de DMCA!",
    "{user2} recibió una visita domiciliaria del doctor {user1}.",
    "{user1} decapitó a {user2}.",
    "{user2} se apedreó ... por una turba furiosa",
    "{user1} demandó que le quitaran los pantalones a {user2}.",
    "{user2} fue KO de un golpe por {user1}.",
    "{user1} envió a {user2} por el agujero de la memoria",
    "{user2} fue un error. - '{user1}'",
    "{user2} fue despedido.",
    "¡{user1} {hits} {user2} con un bate!",
    "{user1} {hits} {user2} with a Taijutsu Kick !.",
    "{user1} {hits} {user2} con X-Gloves !.",
    "{user1} {hits} {user2} con un Jet Punch !.",
    "{user1} {hits} {user2} con una pistola Jet !.",
    "{user1} {hits} {user2} con un United States of Smash !.",
    "{user1} {hits} {user2} with a Detroit Smash !.",
    "{user1} {hits} {user2} with a Texas Smash !.",
    "{user1} {hits} {user2} with a California Smash !.",
    "{user1} {hits} {user2} with a New Hampshire Smash !.",
    "{user1} {hits} {user2} with a Missouri Smash !.",
    "{user1} {hits} {user2} with a Carolina Smash !.",
    "{user1} {hits} {user2} con una pistola King Kong !.",
    "{user1} {hits} {user2} con un bate de béisbol, ¡uno de metal.!.",
    "*Puñetazos serios {user2} *.",
    "*Punzones normales {user2} *.",
    "*Punzones normales consecutivos {user2} *.",
    "*Golpes normales consecutivos a dos manos {user2} *.",
    "*Ignora a {user2} para dejarlos morir de vergüenza *.",
    "*señala a {user2} * ¿Qué pasa con este descarado ... niño perdido?",
    "*Golpea a {user2} con un Tornado de fuego *.",
    "¡{user1} golpea a {user2} en el ojo!",
    "¡{user1} golpea a {user2} en los costados!",
    "¡{user1} empuja a {user2}!",
    "¡{user1} pincha a {user2} con una aguja!",
    "¡{user1} pincha a {user2} con un bolígrafo!",
    "¡{user1} golpea a {user2} con una pistola paralizante!",
    "¡{user2} es secretamente un peludo!",
    "¡Hola a todos! ¡{User1} me está pidiendo que sea malo!",
    "(･ _ ･) ﾉ ⌒ ● ~ * (･. ･;) <- {usuario2}",
    "Toma este {usuario2} \ n (ﾉ ﾟ Д ﾟ) ﾉ)))) ● ~ *",
    "Aquí {user2} mantén presionado este \ n (｀ ・ ω ・) つ ● ~ ＊",
    "(・ _ ・) ノ Ξ ● ~ * {usuario2} \ nDieeeee !!.",
    "(・ ∀ ・) ｒ 鹵 ~ <≪ 巛; ﾟ Д ﾟ) ﾉ \ n * Aerosoles de insectos {user2} *.",
    "(ﾟ Д ﾟ) ﾉ 占 ~ <巛 巛 巛. \ N- {user2} ¡Eres una plaga!",
    "(う -´) づ ︻╦̵̵̿╤── \ (˚☐˚”) / {usuario2}.",
    "{user1} {hits} {user2} con un {item}.",
    "{user1} {hits} {user2} en la cara con un {item}.",
    "{user1} {hits} {user2} alrededor un poco con un {item}.",
    "{user1} {lanza} un {item} a {user2}.",
    "{user1} agarra un {item} y {lo arroja} a la cara de {user2}.",
    "{user1} lanza un {item} en la dirección general de {user2}.",
    "{user1} comienza a abofetear a {user2} tontamente con un {item}.",
    "{user1} fija a {user2} y repetidamente {los golpea} con un {item}.",
    "{user1} agarra un {item} y {hits} {user2} con él.",
    "{user1} ata a {user2} a una silla y {lanza} un {item} hacia ellos.",
    "{user1} dio un empujón amistoso para ayudar a {user2} a aprender a nadar en lava",
    "{user1} acosó a {user2}.",
    "Nyaan se comió la pierna de {user2}. * Nomnomnom *", 
    "{user1} {lanza} una bola maestra a {user2}, la resistencia es inútil.",
    "{usuario1} golpea a {usuario2} con un rayo de acción ... bbbbbb (ง ・ ω ・) ง ==== *",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "¡{user2} se convirtió en una referencia de Jojo!",
    "{user1} acierta a {user2} con {item}.",
    "¡Ronda 2! .. ¿Listo? .. ¡¡LUCHA !!",
    "WhoPixel superará a {user2} hasta el infinito y más allá",
    "{user2} se comió un murciélago y descubrió una nueva enfermedad",
    "{user1} dobló a {user2} en un avión de papel",
    "{user1} le sirvió a {user2} sopa de murciélago.",
    "{user2} fue enviado a su hogar, el planeta de los simios",
    "{user1} echó a {user2} de un tren en movimiento",
    "{user2} acaba de matar al perro de John Wick",
    "{user1} realizó un hechizo Avada Kedavra en {user2}.",
    "{user1} sometió a {user2} a un horno de fuego.",
    "Sakura Haruno se volvió más útil que {user2}",
    "{user1} desconectó el soporte vital de {user2}.",
    "{user1} suscrito {user2} 'a 5 años de mala Internet",
    "¿Sabes qué es peor que los chistes de papá? ¡{User2}!",
    "{user1} tomó todas las cookies de {user2}",
    "{user2} wa mou ....... ¡Shindeiru! - {user1}.",
    "¡{user2} perdió su pieza de carrera!", # Sin juego sin referencia de vida
    "Cállate {user2}, solo eres {user2}.", # Sin juego no hay referencia de vida
    "¡{user1} golpea a {user2} con Aka si anse!", # Sin juego sin referencia de vida
    "@AlphaElias se rasca {user2}", # gato mascota # Pixels - @AlphaElias
    "Majin buu se comió a {user2}", # Dbz
    "Goblin Slayer mata a {user2}", # Goblin Slayer
)

PAT_TEMPLATES = (
    "{user1} acaricia a {user2} en la cabeza.",
    "*frota suavemente la cabeza de {user2}*.",
    "*{user1} mofumofus {user2} 's head*",
    "*{user1} estropea la cabeza de {user2}*",
    "*{user1} frota intensamente la cabeza de {user2} *",
    "El waifu de* {user2} acaricia su cabeza*",
    "* {user2} tiene almohadillas gratis*",
    "No hay palmaditas para {user2}!",
    "Oh no! Todos nos quedamos sin caricias",
    "Esta es una zona designada para no tocar!",
    "No hay palmaditas para {user2}!",
    "{user1} mima a {user2} con almohadillas para la cabeza!",
    "{user2} recibió un headpat gratis!",
    "{user1} acaricia la cabeza {user2} mientras le da una almohada para el regazo",
    "{user1} acaricia agresivamente a {user2}",
    "{user1} acaricia suavemente la cabeza de {user2}",
    "Pat, pat, pat, pat",
    "{user2} no pudo escapar de las almohadillas de {user1}",
    "{user2} .exe ha dejado de funcionar",
    "{user1} frota a {user2} en el cuello",
    "Debe ... extorsionar ... HEADPATS",
    "{user1} acaricia la cabeza de {user2} con una palmadita",
    "{user1} acaricia a {user2} inesperadamente",
    "{user1} acaricia a {user2} con su consentimiento, ¿tal vez?",
    "¡Pat pat, {user2} honto kawaii ne!",
    "{user1} headpats {user2} a 420apm",
    "{user1} bellyrubs {user2}",
    "{user1} acaricia a {user2} amigablemente",
    "¿{user2} usa HEADPATS? O KAWAII KOTO",
    "* headpats.gif se intensifica para {user2} *",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ ᴗ。)",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ",
)

PAT_GIFS = (
    "CgACAgQAAxkBAALRX19Xs7tBdOH1gQwS_rglVRkTbgVYAAKEAgACmQn9UWlyGa_xy9_aGwQ",
    "CgACAgEAAxkBAALRYF9Xs8EnhsDfDpld3ILoqTbzDmwxAAJFAAOJxjlHECanwn69E5QbBA",
)

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ",
)

PING_STRING = (
    "PONG!!",
    "Estoy aquí!",
)

ITEMS = (
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)

HIT = (
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",
)

EYES = [
    ["⌐■", "■"],
    [" ͠°", " °"],
    ["⇀", "↼"],
    ["´• ", " •`"],
    ["´", "`"],
    ["`", "´"],
    ["ó", "ò"],
    ["ò", "ó"],
    ["⸌", "⸍"],
    [">", "<"],
    ["Ƹ̵̡", "Ʒ"],
    ["ᗒ", "ᗕ"],
    ["⟃", "⟄"],
    ["⪧", "⪦"],
    ["⪦", "⪧"],
    ["⪩", "⪨"],
    ["⪨", "⪩"],
    ["⪰", "⪯"],
    ["⫑", "⫒"],
    ["⨴", "⨵"],
    ["⩿", "⪀"],
    ["⩾", "⩽"],
    ["⩺", "⩹"],
    ["⩹", "⩺"],
    ["◥▶", "◀◤"],
    ["◍", "◎"],
    ["/͠-", "┐͡-\\"],
    ["⌣", "⌣”"],
    [" ͡⎚", " ͡⎚"],
    ["≋"],
    ["૦ઁ"],
    ["  ͯ"],
    ["  ͌"],
    ["ළ"],
    ["◉"],
    ["☉"],
    ["・"],
    ["▰"],
    ["ᵔ"],
    [" ﾟ"],
    ["□"],
    ["☼"],
    ["*"],
    ["`"],
    ["⚆"],
    ["⊜"],
    [">"],
    ["❍"],
    ["￣"],
    ["─"],
    ["✿"],
    ["•"],
    ["T"],
    ["^"],
    ["ⱺ"],
    ["@"],
    ["ȍ"],
    ["  "],
    ["  "],
    ["x"],
    ["-"],
    ["$"],
    ["Ȍ"],
    ["ʘ"],
    ["Ꝋ"],
    [""],
    ["⸟"],
    ["๏"],
    ["ⴲ"],
    ["◕"],
    ["◔"],
    ["✧"],
    ["■"],
    ["♥"],
    [" ͡°"],
    ["¬"],
    [" º "],
    ["⨶"],
    ["⨱"],
    ["⏓"],
    ["⏒"],
    ["⍜"],
    ["⍤"],
    ["ᚖ"],
    ["ᴗ"],
    ["ಠ"],
    ["σ"],
    ["☯"],
]

MOUTHS = [
    ["v"],
    ["ᴥ"],
    ["ᗝ"],
    ["Ѡ"],
    ["ᗜ"],
    ["Ꮂ"],
    ["ᨓ"],
    ["ᨎ"],
    ["ヮ"],
    ["╭͜ʖ╮"],
    [" ͟ل͜"],
    [" ͜ʖ"],
    [" ͟ʖ"],
    [" ʖ̯"],
    ["ω"],
    [" ³"],
    [" ε "],
    ["﹏"],
    ["□"],
    ["ل͜"],
    ["‿"],
    ["╭╮"],
    ["‿‿"],
    ["▾"],
    ["‸"],
    ["Д"],
    ["∀"],
    ["!"],
    ["人"],
    ["."],
    ["ロ"],
    ["_"],
    ["෴"],
    ["ѽ"],
    ["ഌ"],
    ["⏠"],
    ["⏏"],
    ["⍊"],
    ["⍘"],
    ["ツ"],
    ["益"],
    ["╭∩╮"],
    ["Ĺ̯"],
    ["◡"],
    [" ͜つ"],
]

EARS = [
    ["q", "p"],
    ["ʢ", "ʡ"],
    ["⸮", "?"],
    ["ʕ", "ʔ"],
    ["ᖗ", "ᖘ"],
    ["ᕦ", "ᕥ"],
    ["ᕦ(", ")ᕥ"],
    ["ᕙ(", ")ᕗ"],
    ["ᘳ", "ᘰ"],
    ["ᕮ", "ᕭ"],
    ["ᕳ", "ᕲ"],
    ["(", ")"],
    ["[", "]"],
    ["¯\\_", "_/¯"],
    ["୧", "୨"],
    ["୨", "୧"],
    ["⤜(", ")⤏"],
    ["☞", "☞"],
    ["ᑫ", "ᑷ"],
    ["ᑴ", "ᑷ"],
    ["ヽ(", ")ﾉ"],
    ["\\(", ")/"],
    ["乁(", ")ㄏ"],
    ["└[", "]┘"],
    ["(づ", ")づ"],
    ["(ง", ")ง"],
    ["⎝", "⎠"],
    ["ლ(", "ლ)"],
    ["ᕕ(", ")ᕗ"],
    ["(∩", ")⊃━☆ﾟ.*"],
]

TOSS = ("Heads", "Tails")

EIGHTBALL = [
    "🟢 Como yo lo veo, sí.",
    "🟡 Preguntar de nuevo más tarde.",
    "🟡 Mejor no te lo diga ahora",
    "🟡 No se puede predecir ahora",
    "🟡 Concéntrate y pregunta de nuevo.",
    "🟡 No cuentes con eso",
    "🟢 Es cierto.",
    "🟢 Definitivamente es así.",
    "🟢 Lo más probable.",
    "🔴 Mi respuesta es no.",
    "🔴 Mis fuentes dicen que no",
    "🔴 Outlook no es tan bueno",
    "🟢 Outlook bueno.",
    "🟡 Respuesta confusa, inténtalo de nuevo.",
    "🟢 Las señales apuntan a sí.",
    "🔴 Muy dudoso",
    "🟢 Sin duda.",
    "🟢 Sí.",
    "🟢 Sí, definitivamente.",
    "🟢 Puede confiar en ello.",
]

DECIDE = ("Yes.", "No.", "Quizás.")

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
    "Me quedé sin mesas, pediré más",
    "Ve a trabajar un poco en lugar de mesas giratorias.",
)
